version: '{build}'
shallow_clone: true

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: cygwin
    - perl_type: strawberry
      perl_version: perl-5.24.3
    - perl_type: strawberry
      perl_version: perl-5.20.3
    - perl_type: strawberry
      perl_version: perl-5.18.4

install:
  - 'call appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% --installdeps -n --with-develop --with-recommends .'

build: off

test_script:
  - 'prove -l t'

matrix:
  fast_finish: true